apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: timetable-redis
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timetable-redis
    spec:
      containers:
        - image: redis:5.0-alpine
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis-claim
